config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :show, :destroy]
  resources :users, only: [:new, :show, :create, :destroy]
  resources :tasks do
    collection do
      post :confirm
    end
  end
  namespace :admin do
    resources :users
    resources :labels, except: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
  validates :name, presence: true
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :detail, presence: true, length: { maximum: 255 }

  enum status: { not_started: 0, started: 1, completed: 2 }
  enum priority: { high: 0, middle: 1, low: 2 }

  scope :by_created_at, -> { order(created_at: :desc) }
  scope :by_expired_at, -> { order(expired_at: :desc) }
  scope :by_priority, -> { order(priority: :asc) }
  scope :search_word, ->(search) { where("title LIKE ?", "%#{search}%") }
  scope :search_status, ->(status) { where(status: status) }

  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  has_many :tasks, dependent: :destroy

  private

  before_destroy { throw(:abort) if User.where(admin: true).count <= 1 && self.admin? }
  before_update { throw(:abort) if User.where(admin: true).count <= 1 && self.admin? }


end

app/controllers/admin/labels_controller.rb
class Admin::LabelsController < ApplicationController
  before_action :admin?
  before_action :set_label, only: %i[edit update destroy]

  def index
    @labels = Label.all
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      flash[:notice] = "ラベルを作成しました！"
      redirect_to admin_labels_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @label.update(label_params)
      flash[:notice] = "ラベルを編集しました！"
      redirect_to admin_labels_path
    else
      render :edit
    end
  end

  def destroy
    @label.destroy
    flash[:notice] = "ラベルを削除しました！"
    redirect_to admin_labels_path
  end

  private

  def admin?
    unless current_user.admin?
      redirect_to tasks_path
      flash[:notice] = "管理者権限がありません"
    end
  end

  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[ edit update show destroy ]
  before_action :admin?

  def index
    @users = User.all.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'ユーザーを作成'
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'ユーザーを更新'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'ユーザーを削除'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def admin?
    unless current_user.admin?
      redirect_to tasks_path
      flash[:notice] = "管理者権限がありません"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[ new create ]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy] 
  skip_before_action :login_required
  
  def index
    @tasks = current_user.tasks.by_created_at
    @tasks = current_user.tasks.by_expired_at if params[:sort_expired].present?
    @tasks = current_user.tasks.by_priority if params[:sort_priority].present?
    if params[:search].present? && params[:status].present? && params[:label_id].present?
      @tasks = current_user.tasks.search_word(params[:search]).search_status(params[:status]).joins(:labels).where(labels: { id: params[:label_id] })
    elsif params[:search].present? && params[:status].present?
      @tasks = current_user.tasks.search_word(params[:search]).search_status(params[:status])
    elsif params[:search].present? && params[:label_id].present?
      @tasks = current_user.tasks.search_word(params[:search]).joins(:labels).where(labels: { id: params[:label_id] })
    elsif params[:status].present? && params[:label_id].present?
      @tasks = current_user.tasks.search_status(params[:status]).joins(:labels).where(labels: { id: params[:label_id] })
    elsif params[:search].present?
      @tasks = current_user.tasks.search_word(params[:search])
    elsif params[:status].present?
      @tasks = current_user.tasks.search_status(params[:status])
    elsif params[:label_id].present?
      @tasks = current_user.tasks.joins(:labels).where(labels: { id: params[:label_id] })
    else
    end
    @tasks = @tasks.page(params[:page]).per(10)
  end

  def new
    @task = Task.new
  end

  def confirm
    @task = current_user.tasks.build(task_params)
    render :new if @task.invalid?
  end

  def create
    # binding.pry
    @task = current_user.tasks.build(task_params)
    @user = User.find(@task.user.id)
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to user_path(@user.id)
        flash[:notice] = "タスクが登録出来ました!"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:notice] = "タスクを編集しました!"
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = "タスクを削除しました!"
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :detail, :expired_at, :status, :priority, { label_ids: [] })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[ new create ]
  before_action :unable_new, only: %i[ new ]

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if @user == current_user
      @user
    else
      redirect_to tasks_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def unable_new
    redirect_to tasks_path if current_user.present?
  end
end

app/helpers/admin/labels_helper.rb
module Admin::LabelsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tasks_path
    elsif action_name == 'edit'
      task_path(@task.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/labels/edit.html.erb
<h4>ラベル編集画面</h4>

<%= form_with(model: @label, local: true, url: admin_label_path) do |form| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= @label.errors.count %>件のエラーがあるよ</h2>
      <ul>
      <% @label.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-3"><%= form.label :name %></div>
  <div><%= form.text_field :name %></div>

  <%= form.submit %>
<% end %>

<p><%= link_to '戻る', admin_labels_path%></p>

app/views/admin/labels/index.html.erb
<h3>ラベル一覧</h3>

<div><%= link_to 'ラベル新規登録', new_admin_label_path, type: "button", class: "btn btn-primary mb-3" %></div>

<table class="table">
  <thead>
    <tr>
      <th class="col-6">ラベル名</th>
    </tr>
  </thead>
  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= link_to '編集', edit_admin_label_path(label.id), type: "button", class: "btn btn-outline-success btn-sm" %></td>
        <td><%= link_to '削除', admin_label_path(label.id), method: :delete, data: { confirm: '本当に削除しますか?' }, type: "button", class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p class="mt-3"><%= link_to '戻る', admin_users_path %></p

app/views/admin/labels/new.html.erb
<h4 class="mb-3">ラベル作成</h4>

<%= form_with(model: @label, local: true, url: admin_labels_path ) do |form| %>
  <% if @label.errors.any? %>
  <div id="error_explanation">
    <h4>Found <%= @label.errors.count %> errors!</h4>
      <ul>
        <% @label.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
  <% end %>

    <div class="mt-3"><%= form.label :name %></div>
    <div><%= form.text_field :name %></div>

  <div class="mt-3"><%= form.submit %></div>
<% end %>

<p class="mt-3"><%= link_to '戻る', admin_labels_path %></p>

app/views/admin/users/edit.html.erb
<h2>管理者専用</h2>

<h3>ユーザー情報更新</h3>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin, @user], local:true ) do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.label :admin %>
  <%= form.check_box :admin, {} , true, false %>

  <%= form.label :notadmin %>
  <%= form.check_box :admin, {} , false, true %>

  <%= form.submit %>

<% end %>

<%= link_to 'ユーザー一覧', admin_users_path %>

app/views/admin/users/index.html.erb
<h2>管理者専用画面</h2>
<p><%= notice %></p>

<h3>ユーザー一覧</h3>

<table class="table">
<tr>
  <th>ユーザー名</th>
  <th>合計タスク数</th>
  <th>管理者権限</th>
</tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.tasks.count %></td>
    <td><%= user.admin %></td>
    <td><%= link_to '詳細', admin_user_path(user.id) %></td>
    <td><%= link_to '編集', edit_admin_user_path(user.id) %></td>
    <td><%= link_to '削除', admin_user_path(user.id), method: :delete, data: { confirm: t('本当に削除しますか?') }%></td>
  </tr> 
<% end %>
  <%= link_to '管理者ユーザー作成', new_admin_user_path %>
  <%= link_to 'ラベル管理画面', admin_labels_path %>
</table>

app/views/admin/users/new.html.erb
<h2>管理者専用画面</h2>

<h3>ユーザー新規作成</h3>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local:true, url:admin_users_path) do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.label :admin %>
  <%= form.check_box :admin, {} , true, false %>

  <%= form.submit %>
  
<% end %>

app/views/admin/users/show.html.erb
<h2><%= @user.name %>のページ</h2>

<p>メールアドレス: <%= @user.email %></p>

<%= link_to "新規登録", new_user_path %> 
<%= link_to "戻る", tasks_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyouExam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "プロフィール", user_path(current_user.id) %>
      <%= button_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "アカウントを作成する", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true, url:choose_new_or_edit ) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあるよ</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="mt-3"><%= form.label :title %></div>
    <div><%= form.text_field :title %></div>

    <div class="mt-3"><%= form.label :detail %></div>
    <div><%= form.text_area :detail %></div>

    <div class="mt-3"><%= form.label :expired_at %></div>
    <div><%= form.date_select :expired_at %></div>

    <div class="mt-3"><%= form.label :status %></div>
    <%= form.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.task.status.#{k}"), k]} %>
    
    <div class="mt-3"><%= form.label :priority %></div>
    <%= form.select :priority, Task.priorities.keys.map {|k| [I18n.t("enums.task.priority.#{k}"), k]} %>

    <div class="mt-3"><%= form.label :label %></div>
      <% Label.all.each do |label| %>
        <%= form.check_box :label_ids, { multiple: true, disabled: label[:disabled], include_hidden: false }, label[:id] %>
        <%= form.label :label_ids, label.name, value: label[:id] %>
    <% end %>

  <div class="mt-3"><%= form.submit %></div>
<% end %>

app/views/tasks/confirm.html.erb
<%= form_with(model: @task, url: tasks_path, local: true) do |form| %>
  <h4 class="mb-3">確認画面</h4>
  <p><strong>タスク名:&ensp;</strong>
    <%= form.hidden_field :title %>
    <%= @task.title %></p>
  
  <p><strong>詳細:&ensp;</strong>
    <%= form.hidden_field :detail %>
    <%= @task.detail %></p>
  
  <p><strong>終了期限:&ensp;</strong>
    <%= form.hidden_field :expired_at %>
    <%= l @task.expired_at, format: :date_only %></p>
  
  <p><strong>ステータス:&ensp;</strong>
    <%= form.hidden_field :status %>
    <%= @task.status_i18n %></p>
  
  <p><strong>優先度:&ensp;</strong>
    <%= form.hidden_field :priority %>
    <%= @task.priority_i18n %></p>

  <p><strong>ラベル:&ensp;</strong>
    <% @task.labels.each do |label| %>
    <%= form.hidden_field :label_ids, multiple: true, value: label.id %>
    <span class ="badge bg-secondary text-light m-1"><%= label.name %></span>
    <% end %>
  </p>
  
  <div class="mt-1">
    <%= form.submit %>
  </div>

  <div class="mt-2">
    <%= form.submit "戻る", name: "back" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h2>タスク編集</h2>

<%= render 'form' %>

<%= link_to '詳細', task_path(@task.id) %>
<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<h3>タスク一覧</h3>

<%= form_with url: tasks_path, method: :get, local: true do |form| %>
  タスク名<%= form.text_field :search, placeholder: "検索" %>
  ステータス<%= form.select :status, options_for_select([["指定なし", ""]].concat(Task.statuses.map { |k, v| [I18n.t("enums.task.status.#{k}"), k] })), {} %>
  ラベル<%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %></span>
  <%= form.submit '検索', name: nil %>
<% end %>
</div>

<div><%= link_to '新規登録', new_task_path, type: "button", class: "btn btn-primary mb-3" %></div>

<table class="table">
  <thead>
    <tr>
      <th class="col-2">タスク名</th>
      <th class="col-1"><%= link_to "終了期限▼", tasks_path(sort_expired: "true") %></th>
      <th class="col-1">登録日時</th>
      <th class="col-1">作成者</th>
      <th class="col-1">ステータス</th>
      <th class="col-1"><%= link_to "優先度▼", tasks_path(sort_priority: "true") %></th>
      <th class="col-1">ラベル</th>
      <th class="col-2" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="task_row"><%= task.title %></td>
        <td><%= l task.expired_at, format: :date_only %></td>
        <td><%= l task.created_at, format: :short %></td>
        <td><%= task.user.name %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td>
        <% task.labels.each do |label| %>
          <span class ="badge bg-secondary text-light m-1"><%= label.name %></span>
        <% end %>
        </td>
        <td><%= link_to '詳細', task_path(task.id), type: "button", class: "btn btn-outline-primary btn-sm" %></td>
        <td><%= link_to '編集', edit_task_path(task.id), type: "button", class: "btn btn-outline-success btn-sm" %></td>
        <td><%= link_to '削除', task_path(task.id), method: :delete, data: { confirm: '本当に削除しますか?' }, type: "button", class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h2>タスク投稿</h2>

<%= render 'form' %>

<p><%= link_to '戻る', tasks_path %></p>

app/views/tasks/show.html.erb
<h4>タスク詳細</h4>

<p><strong>タスク名:&ensp;</strong><%= @task.title %></p>
<p><strong>詳細:&ensp;</strong><%= @task.detail %></p>
<p><strong>終了期限:&ensp;</strong><%= l @task.expired_at, format: :date_only %></p>
<p><strong>ステータス:&ensp;</strong><%= @task.status %></p>
<p><strong>優先度:&ensp;</strong><%= @task.priority %></p>
<p><strong>ラベル:&ensp;</strong>
  <% @task.labels.each do |label| %>
    <span class ="badge bg-secondary text-light m-1"><%= label.name %></span>
  <% end %>
</p>

<p><%= link_to '戻る', tasks_path %></p>

app/views/users/new.html.erb
<h2>アカウントを作成する</h2>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "つのエラー") %>があって<%= @user.name %>が登録できませんでした。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |form| %>  
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p>メールアドレス:<%= @user.email%></p>
<br>
<% if @current_user.admin?%>
  <%= link_to '管理者権限', admin_users_path %>
<% end %>

<h3><%= @user.email %>のタスク</h3>
<table>
  <thead>
    <tr>
      <th class="col-1">作成者</th>
      <th class="col-2">タスク名</th>
      <th class="col-1"><%= link_to "終了期限▼", tasks_path(sort_expired: "true") %></th>
      <th class="col-1">登録日時</th>
      <th class="col-1">ステータス</th>
      <th class="col-1"><%= link_to "優先度▼", tasks_path(sort_priority: "true") %></th>
      <th class="col-1">ラベル</th>
      <th class="col-2" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td><%= task.user.name %></td>
        <td class="task_row"><%= task.title %></td>
        <td><%= l task.expired_at, format: :date_only %></td>
        <td><%= l task.created_at, format: :short %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td>
        <% task.labels.each do |label| %>
          <span class ="badge bg-secondary text-light m-1"><%= label.name %></span>
        <% end %>
        </td>
        <td><%= link_to '詳細', task_path(task.id), type: "button", class: "btn btn-outline-primary btn-sm" %></td>
        <td><%= link_to '編集', edit_task_path(task.id), type: "button", class: "btn btn-outline-success btn-sm" %></td>
        <td><%= link_to '削除', task_path(task.id), method: :delete, data: { confirm: '本当に削除しますか?' }, type: "button", class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  
  <%= link_to '新規登録', new_task_path %>